export enum ClassLevel {
  CLASS_LEVEL_1 = 'Lớp 1',
  CLASS_LEVEL_2 = 'Lớp 2',
  CLASS_LEVEL_3 = 'Lớp 3',
  CLASS_LEVEL_4 = 'Lớp 4',
  CLASS_LEVEL_5 = 'Lớp 5',
}

export enum QuestionType {
  ONE_ANSWER = 'ONE_ANSWER',
  MULTIPLE_ANSWERS = 'MULTIPLE_ANSWERS',
}

export enum QuestionFormat {
  TEXT_QUESTION_TEXT_ANSWERS = 'TEXT_QUESTION_TEXT_ANSWERS',
  MEDIA_QUESTION_TEXT_ANSWERS = 'MEDIA_QUESTION_TEXT_ANSWERS',
  TEXT_QUESTION_MEDIA_ANSWERS = 'TEXT_QUESTION_MEDIA_ANSWERS',
  MEDIA_QUESTION_MEDIA_ANSWERS = 'MEDIA_QUESTION_MEDIA_ANSWERS',
}

export enum FileType {
  TEXT = 'TEXT',
  NOT_EXISTED = 'NOT_EXISTED',
  EXISTED = 'EXISTED',
}
